'use client';
import { FormEvent, useState } from 'react';
import type { Book, Order } from '../../db/store';

const peso=new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0});
export default function OwnerDashboard({books:initialBooks,orders:initialOrders,email,signOutPath}:{books:Book[];orders:Order[];email:string;signOutPath:string}) {
  const [books,setBooks]=useState(initialBooks); const [orders,setOrders]=useState(initialOrders); const [adding,setAdding]=useState(false); const [error,setError]=useState('');
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setAdding(true);setError('');const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());const response=await fetch('/api/admin/books',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as {error?:string};if(response.ok){location.reload()}else{setError(data.error||'Could not add book');setAdding(false)}}
  async function bookStatus(id:number,status:Book['status']){const previous=books;setBooks(books.map(b=>b.id===id?{...b,status}:b));const response=await fetch('/api/admin/books',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});if(!response.ok)setBooks(previous)}
  async function orderStatus(id:string,status:string){const previous=orders;setOrders(orders.map(o=>o.id===id?{...o,status}:o));const response=await fetch('/api/admin/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});if(!response.ok)setOrders(previous);else location.reload()}
  const revenue=orders.filter(o=>['paid','shipped','completed'].includes(o.status)).reduce((sum,o)=>sum+o.total,0);
  return <main className="dashboard"><aside className="dashboard-sidebar"><a href="/" className="brand"><span className="brand-mark">D</span><span>Dog-Eared Books</span></a><nav><a href="#overview">Overview</a><a href="#orders">Claims</a><a href="#inventory">Inventory</a></nav><div><small>{email}</small><a href={signOutPath}>Sign out</a></div></aside><div className="dashboard-main"><header><div><p className="eyebrow">Seller dashboard</p><h1 id="overview">Your book drop, at a glance.</h1></div><a href="/" target="_blank">View storefront ↗</a></header><section className="metrics"><div><span>Available books</span><strong>{books.filter(b=>b.status==='available').length}</strong></div><div><span>Open claims</span><strong>{orders.filter(o=>o.status==='pending_payment').length}</strong></div><div><span>Confirmed sales</span><strong>{peso.format(revenue)}</strong></div></section>
  <section className="admin-section" id="orders"><div className="admin-heading"><div><p className="eyebrow">Buyer claims</p><h2>Orders to process</h2></div><span>{orders.length} total</span></div>{orders.length?<div className="order-list">{orders.map(order=><article key={order.id}><div className="order-top"><div><strong>{order.code}</strong><span>{new Date(order.created_at+'Z').toLocaleDateString()}</span></div><select value={order.status} onChange={e=>orderStatus(order.id,e.target.value)} aria-label={`Status for ${order.code}`}><option value="pending_payment">Pending payment</option><option value="paid">Paid</option><option value="shipped">Shipped</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><h3>{order.customer_name}</h3><p>{order.books}</p><div className="order-contact"><span>{order.facebook_profile}</span><span>{order.phone}</span><span>{order.delivery_method}</span></div><strong className="order-total">{peso.format(order.total)}</strong></article>)}</div>:<div className="empty-state">New buyer claims will appear here.</div>}</section>
  <section className="admin-section" id="inventory"><div className="admin-heading"><div><p className="eyebrow">Inventory</p><h2>Add a new arrival</h2></div></div><form className="add-book-form" onSubmit={add}><label>Title<input name="title" required maxLength={120}/></label><label>Author<input name="author" required maxLength={100}/></label><label>Price (PHP)<input name="price" type="number" min="0" required/></label><label>Condition<select name="condition"><option>Like new</option><option>Very good</option><option>Good</option><option>Well loved</option></select></label><label>Cover color<select name="tone"><option value="coral">Coral</option><option value="blue">Blue</option><option value="ochre">Ochre</option><option value="mint">Mint</option></select></label><label className="wide">Condition notes<textarea name="description" rows={2} maxLength={400}/></label>{error&&<p className="form-error wide">{error}</p>}<button disabled={adding}>{adding?'Adding…':'+ Add to drop'}</button></form><div className="inventory-list">{books.map(book=><div key={book.id}><span className={`mini-cover ${book.tone}`}>{book.title.slice(0,1)}</span><span><strong>{book.title}</strong><small>{book.author} · {peso.format(book.price)}</small></span><select value={book.status} onChange={e=>bookStatus(book.id,e.target.value as Book['status'])} aria-label={`Status for ${book.title}`}><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option></select></div>)}</div></section></div></main>;
}
