create table public.seller_updates (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 2000),
  image_url text,
  created_at timestamptz not null default now()
);

create index idx_seller_updates_created
on public.seller_updates(created_at desc);

alter table public.seller_updates enable row level security;

create policy "Anyone can read seller updates"
on public.seller_updates for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.seller_updates from anon, authenticated;
