create extension if not exists pgcrypto;

create table public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  price integer not null check (price >= 0),
  condition text not null,
  status text not null default 'available' check (status in ('available','reserved','sold')),
  tone text not null default 'coral',
  description text not null default '',
  image_url text,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  customer_name text not null,
  facebook_profile text not null,
  phone text not null,
  delivery_method text not null,
  address text not null default '',
  notes text not null default '',
  total integer not null default 0,
  status text not null default 'pending_payment' check (status in ('pending_payment','paid','shipped','completed','cancelled')),
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  book_id bigint not null unique references public.books(id),
  price integer not null
);

create index idx_books_status_created on public.books(status, created_at desc);
create index idx_orders_status_created on public.orders(status, created_at desc);
create index idx_order_items_order on public.order_items(order_id);

alter table public.books enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Anyone can browse books"
on public.books for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.books from anon, authenticated;
revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;

create or replace function public.create_book_claim(
  p_book_ids bigint[],
  p_customer_name text,
  p_facebook_profile text,
  p_phone text,
  p_delivery_method text,
  p_address text default '',
  p_notes text default ''
)
returns table(claim_code text, claim_total integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ids bigint[];
  v_available_count integer;
  v_order_id uuid := gen_random_uuid();
  v_code text := 'READ-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 7));
begin
  select array_agg(distinct item order by item) into v_ids
  from unnest(p_book_ids) as item;

  if coalesce(cardinality(v_ids), 0) < 1 or cardinality(v_ids) > 20 then
    raise exception 'INVALID_BOOK_COUNT';
  end if;

  perform id from public.books
  where id = any(v_ids)
  order by id
  for update;

  select count(*) into v_available_count
  from public.books
  where id = any(v_ids) and status = 'available';

  if v_available_count <> cardinality(v_ids) then
    raise exception 'BOOK_UNAVAILABLE';
  end if;

  insert into public.orders (id,code,customer_name,facebook_profile,phone,delivery_method,address,notes)
  values (v_order_id,v_code,left(trim(p_customer_name),80),left(trim(p_facebook_profile),200),left(trim(p_phone),30),left(trim(p_delivery_method),40),left(trim(coalesce(p_address,'')),300),left(trim(coalesce(p_notes,'')),300));

  insert into public.order_items (order_id,book_id,price)
  select v_order_id,id,price from public.books where id = any(v_ids);

  update public.books set status = 'reserved' where id = any(v_ids);

  update public.orders
  set total = (select coalesce(sum(price),0) from public.order_items where order_id = v_order_id)
  where id = v_order_id;

  return query select o.code,o.total from public.orders o where o.id = v_order_id;
end;
$$;

revoke all on function public.create_book_claim(bigint[],text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.create_book_claim(bigint[],text,text,text,text,text,text) to service_role;

insert into public.books (title,author,price,condition,tone,description) values
('The Seven Husbands of Evelyn Hugo','Taylor Jenkins Reid',320,'Very good','coral','Clean copy with light shelf wear. No annotations.'),
('Before the Coffee Gets Cold','Toshikazu Kawaguchi',280,'Like new','blue','Almost new with a crisp spine and clean pages.'),
('The Midnight Library','Matt Haig',300,'Very good','ochre','A tidy copy with a small crease on the back cover.'),
('Convenience Store Woman','Sayaka Murata',240,'Good','mint','Loved but well-kept. Minor tanning along page edges.');
